In [4]:
import pandas as pd
import matplotlib.pyplot as plot

In [14]:
state_master_df = pd.read_csv("../data/state-master-data.csv")

In [15]:
state_master_df.head(10)

,Unnamed: 0,date,state,abbr,lat,lon,population,fips,cases,deaths,total_doses_administered,doses_administered_per_100k,percent_vaccinated
0,0,2021-03-02,Alabama,AL,32.601011,-86.680736,4903185,1,494421,9991,972161,19827.0,19.83
1,1,2021-03-02,Alaska,AK,61.302501,-158.775020,731545,2,58383,290,269941,36900.0,36.90
2,2,2021-03-02,Arizona,AZ,34.168219,-111.930907,7278717,4,819281,16065,1889742,25963.0,25.96
3,3,2021-03-02,Arkansas,AR,34.751928,-92.131378,3017804,5,322949,5254,670815,22229.0,22.23
4,4,2021-03-02,California,CA,37.271875,-119.270415,39512223,6,3577497,52774,9497125,24036.0,24.04
5,5,2021-03-02,Colorado,CO,38.997934,-105.550567,5758736,8,432939,6054,1428854,24812.0,24.81
6,6,2021-03-02,Connecticut,CT,41.518784,-72.757507,3565287,9,283128,7658,1040154,29174.0,29.17
7,7,2021-03-02,Delaware,DE,39.145251,-75.418921,973764,10,87193,1426,225417,23149.0,23.15
8,8,2021-03-02,District of Columbia,DC,38.899349,-77.014567,705749,11,40767,1019,199212,28227.0,28.23
9,9,2021-03-02,Florida,FL,27.975728,-83.833017,21477737,12,1918092,31134,5077891,23643.0,23.64

In [16]:
state_master_df.drop(columns={"Unnamed: 0"}, inplace=True)

In [17]:
state_master_df.corr()

,lat,lon,population,fips,cases,deaths,total_doses_administered,doses_administered_per_100k,percent_vaccinated
lat,1.000000,-0.050076,-0.281456,0.105137,-0.299361,-0.264759,-0.261412,0.440868,0.440906
lon,-0.050076,1.000000,0.040734,0.229146,0.018265,0.122861,0.033944,-0.345745,-0.345770
population,-0.281456,0.040734,1.000000,-0.076087,0.989305,0.947767,0.995505,-0.353194,-0.353140
fips,0.105137,0.229146,-0.076087,1.000000,-0.102439,-0.097876,-0.086749,0.066028,0.066052
cases,-0.299361,0.018265,0.989305,-0.102439,1.000000,0.945871,0.982599,-0.356330,-0.356304
deaths,-0.264759,0.122861,0.947767,-0.097876,0.945871,1.000000,0.939992,-0.356695,-0.356673
total_doses_administered,-0.261412,0.033944,0.995505,-0.086749,0.982599,0.939992,1.000000,-0.305836,-0.305772
doses_administered_per_100k,0.440868,-0.345745,-0.353194,0.066028,-0.356330,-0.356695,-0.305836,1.000000,1.000000
percent_vaccinated,0.440906,-0.345770,-0.353140,0.066052,-0.356304,-0.356673,-0.305772,1.000000,1.000000